services:

  api:
    build: ./api
    restart: always
    env_file: .env
    volumes:
      - ./datasets:/data/datasets:rw
      - ./common:/app/common:ro
    ports:
      - "8000:8000"

  bot:
    build: ./bot
    restart: always
    env_file: .env
    depends_on:
      - api
